version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dropface
      MYSQL_USER: dropface         # Optional: Additional user
      MYSQL_PASSWORD: dropface # Optional: Password for the additional user
    volumes:
      - mysql-data:/var/lib/mysql # Persistent storage for MySQL data

volumes:
  mysql-data:
